spring:
  profiles:
    active: dev
  application:
    name: Poc
  datasource:
    url: jdbc:mariadb://localhost:3307/poc_db
    username: root
    password: example
    driver-class-name: org.mariadb.jdbc.Driver
  jpa: 
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect 
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
server:
  servlet:
    context-path: /api
  jwt:
    secret-key: ${jwt.secret}
    expiration: 864000000 # 1 jour en ms 
google:
  api:
    key: ${google.api.key}
    url: https://maps.googleapis.com/maps/api/distancematrix/json
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG